[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/packages/netlification"
disabled = false
ignoreConfig = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/packages/shortcodes"
disabled = false
ignoreConfig = false

[[imports]]
path = "github.com/kaushalmodi/hugo-debugprint"
disabled = false
