################################################################################
# this is the default configuration for dnb-hugo-garuda
# you can overwrite the values in this file by adding them to your own config
# either under [[params.garuda]] or in a file config/_default/params.garuda.toml
################################################################################

################################################################################
# setup Algolia search
################################################################################
use_algolia=false

test="bla"
