[module]

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap5"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/renderhooks"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/robots"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/shortcodes"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/sitemap"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/favicon"

[[module.imports]]
path = "github.com/kaushalmodi/hugo-debugprint"
